// Script Include: HcConnectorEcsLifecycleAction
// HAND-WRITTEN TEMPLATE - do not paste this file directly into ServiceNow.
// The deployable version is generated by scripts/build-script-include.js,
// which inlines lib/credentialProvider.js (module.exports stripped) at the
// marker below, producing
// docs/generated/HcConnectorEcsLifecycleAction.generated.js - paste THAT.
// A real-PDI test with this file pasted as-is failed with "createProvider
// is not defined" - createCredentialProvider() is a bare function, not a
// Class.create() class, so it's only visible within whichever ONE Script
// Include file it's physically concatenated into (same reason
// HcConnectorEcsSync.js needed this same treatment) - it does not become
// globally available just because some other Script Include happened to
// load it first.
//
// HC ITOM Connector - Day-2 operations, first slice (start/stop/reboot for
// ECS instances). Everything discovered so far only ever READS the cloud
// account; this is the first artifact in this project that WRITES to it.
//
// Design choice: reuses HuaweiECSDiscovery's already real-PDI-verified
// _sign() method directly (new HuaweiECSDiscovery(config)._sign(req)) rather
// than duplicating the SDK-HMAC-SHA256 crypto block a ninth time. This is
// the same cross-Script-Include delegation HcConnectorEcsSync.js already
// uses for fetch/reconcile - HuaweiECSDiscovery.js is untouched (frozen,
// real-PDI verified), only read from. _sign() honors config.accessKey/
// secretKey via HuaweiECSDiscovery's own _explicitCredential mechanism
// (confirmed in that file's initialize()/_getCredential()), so no gs.
// getProperty() call happens here at all - credentials still flow through
// HC Cloud Account.auth_mode -> createCredentialProvider(), same as every
// sync orchestrator.
//
// Which account/region a given CI belongs to is resolved via
// HC Resource Sync State (account/region/native_key columns, keyed by
// resource_type='ecs' + ci=<this CI's sys_id>) - the same table every sync
// orchestrator already writes, just read here instead.
//
// Huawei's batch action API (POST /v1/{project_id}/cloudservers/action,
// Nova-compatible os-start/os-stop/reboot shape) - request body built by
// lib/ecsLifecycleAction.js, mirrored inline below (ServiceNow scoped
// scripts cannot require() - keep both in sync, covered by
// check-mirror-drift.js's ninth PAIRS entry).
//
// Response shape real-PDI confirmed: HTTP 200 with {"job_id": "<uuid>"} -
// not an empty body as first assumed. performAction() checks Huawei's own
// async job-tracking endpoint (GET /v1/{project_id}/jobs/{job_id}) once,
// immediately after issuing the action, so the return value distinguishes
// "the job already succeeded" from "the job is still running" from "the
// job failed" - a real gap found via real-PDI testing: a first stop
// attempt against a since-deleted instance produced an HTTP 200 that meant
// nothing, and without checking the job there was no way to tell that
// apart from a real success.
//
// ONE immediate check, not a multi-attempt wait-and-poll loop: a real-PDI
// test of an earlier version (looping with gs.sleep() between attempts)
// failed with `com.glide.script.fencing.MethodNotAllowedException:
// Function sleep is not allowed in scope x_2021019_huawei_0` - gs.sleep()
// is fenced (blocked) for custom scoped apps on this instance, a genuine
// platform restriction, not a bug to work around by trying harder. The
// practical alternative: check once without blocking, and expose
// checkJobStatus(ciSysId, jobId) as a standalone public method so the
// caller (or a follow-up Background Script) can check again later if the
// first check finds the job still running. See docs/ARCHITECTURE.md's
// "Day-2 operations" section for the fuller writeup, including the same
// latent risk in every Discovery file's gs.sleep()-based retry/backoff
// (never yet triggered by a real retryable HTTP status, so never
// real-PDI-exercised either - flagged, not fixed preemptively here).
//
// performResize() (added after start/stop/reboot were real-PDI verified)
// targets a different, per-server Huawei endpoint (POST /v1/{project_id}/
// cloudservers/{server_id}/resize, not the batch .../cloudservers/action
// used above) but reuses everything else: _resolveContext() for account/
// region, disco._sign() for signing, _extractJobId()/_fetchJobStatus() for
// the same single-check job-status pattern. Huawei documents a hard
// prerequisite (instance must already be SHUTOFF) that this code does NOT
// pre-check - consistent with how performAction() above was built (let
// Huawei's own API surface the real rejection-error shape, then fix based
// on what real-PDI testing actually shows, rather than guessing at
// pre-validation logic). Real-PDI verified end to end: job reached SUCCESS
// (~38s wall-clock), flavor change independently confirmed on the Huawei
// Cloud console. Found and fixed a real scoped-app restriction along the
// way, in HcConnectorEcsLifecycleAjax.js (the GlideAjax bridge this needed):
// AbstractAjaxProcessor must be referenced as global.AbstractAjaxProcessor
// from inside a scoped app.
//
// performAttach()/performDetach() (added alongside resize) target Huawei's
// disk-attach/detach endpoints, researched the same way (WebSearch/WebFetch
// against Huawei's published docs, not guessed): POST /v1/{project_id}/
// cloudservers/{server_id}/attachvolume (body built by
// lib/ecsLifecycleAction.js's buildAttachRequestBody(), mirrored below same
// as the others) and DELETE /v1/{project_id}/cloudservers/{server_id}/
// detachvolume/{volume_id} (no request body at all - just an optional
// ?delete_flag=1 query param for a forced detach, so there's no
// buildDetachRequestBody() to mirror; the wrapper builds that path/query
// directly). Both return the same async {"job_id": "..."} shape, reusing
// _extractJobId()/_fetchJobStatus(). Real-PDI verified end to end: attach
// job reached SUCCESS (~3s), detach job reached SUCCESS (~2.5s), disk's
// final "available" state independently confirmed on the Huawei Cloud
// console. Both act on the same ECS CI (_resolveContext(ciSysId) - the
// target is still "this VM instance", volumeId is a separate free-form
// input, same shape as performResize()'s flavorRef), not a lookup against a
// separate EVS CI.
//
// HC Day-2 Action Log (added after all six actions were real-PDI verified):
// every performX() method now writes one row per invocation (via
// _insertActionLog()) and checkJobStatus() updates that row when it's
// called again (via _updateActionLogByJobId()) - the real gap this closes
// is that a UI Action's info message is a one-time popup, so if the first
// job-status check wasn't terminal yet, there was no way to learn the final
// SUCCESS/FAIL outcome without Background Scripts or the Huawei Cloud
// console. pollPendingActionLogs() (called by the new
// scheduled-jobs/hc_connector_day2_job_poller.js) periodically re-checks
// every still-pending row so the CI form's own related list eventually
// shows the real outcome without anyone having to go looking for it.

// __HC_CONNECTOR_INLINED_LIB__

var HcConnectorEcsLifecycleAction = Class.create();
HcConnectorEcsLifecycleAction.prototype = {
    initialize: function() {
        this.SCOPE = 'x_2021019_huawei_0';
        this.ACCOUNT_TABLE = this.SCOPE + '_hc_cloud_account';
        this.REGION_TABLE = this.SCOPE + '_hc_cloud_region';
        this.SYNC_STATE_TABLE = this.SCOPE + '_hc_resource_sync_state';
        this.ACTION_LOG_TABLE = this.SCOPE + '_hc_day2_action_log';
        this.RESOURCE_TYPE = 'ecs';
    },

    // ------------------------------------------------------------------
    // UI Action condition helper - true only for CIs this connector
    // actually discovered (never show Start/Stop/Reboot on an unrelated
    // cmdb_ci_vm_instance from another Discovery source).
    // ------------------------------------------------------------------
    isManaged: function(ciSysId) {
        return !!this._resolveContext(ciSysId);
    },

    // ------------------------------------------------------------------
    // Entry point
    // ------------------------------------------------------------------
    // @param ciSysId - cmdb_ci_vm_instance sys_id
    // @param action - 'start'|'stop'|'reboot'
    // @param opts - { hard: boolean } - hard=true requests HARD (power-cycle) instead of SOFT (graceful)
    // @returns {{status: number, body: string, jobId: string|null, jobStatus: string|null}}
    //   jobStatus is null when the response had no job_id to check (defensive
    //   fallback for the originally-assumed empty-body shape, in case a
    //   future action type doesn't return one); otherwise it's whatever
    //   Huawei's job endpoint reported at the single check point performed
    //   here - 'SUCCESS' if the job had already finished, or a real
    //   in-progress value (e.g. 'RUNNING'/'INIT') if not, in which case call
    //   checkJobStatus(ciSysId, jobId) again later rather than assuming
    //   either outcome. A job already reporting FAIL at this check point
    //   throws rather than returning, same as an HTTP error - both mean "the
    //   caller's requested action did not happen."
    performAction: function(ciSysId, action, opts) {
        var ctx = this._resolveContext(ciSysId);
        if (!ctx) {
            throw new Error('CI ' + ciSysId + ' has no active HC Resource Sync State row for resource_type=ecs - not managed by this connector');
        }

        var provider = createCredentialProvider(ctx.account.auth_mode, {
            propertyReader: function(name) { return gs.getProperty(gs.getCurrentScopeName() + '.' + name); },
            accountId: ctx.account.account_id
        });
        var credentials = provider.getCredentials(); // throws NotImplemented for 'agency' - surfaces as a real error to the caller

        var disco = new HuaweiECSDiscovery({
            region: ctx.region.region,
            projectId: ctx.region.project_id,
            accessKey: credentials.accessKey,
            secretKey: credentials.secretKey
        });

        var host = 'ecs.' + ctx.region.region + '.myhuaweicloud.com';
        var pathname = '/v1/' + ctx.region.project_id + '/cloudservers/action';
        var body = JSON.stringify(this._buildActionRequestBody(action, ctx.nativeKey, opts));
        var paramsStr = opts ? JSON.stringify(opts) : '';

        var signed = disco._sign({ method: 'POST', pathname: pathname, host: host, body: body });

        var request = new sn_ws.RESTMessageV2();
        request.setHttpMethod('POST');
        request.setEndpoint('https://' + host + pathname);
        request.setRequestHeader('Content-Type', signed['Content-Type']);
        request.setRequestHeader('X-Sdk-Date', signed['X-Sdk-Date']);
        request.setRequestHeader('Authorization', signed['Authorization']);
        request.setRequestHeader('host', host);
        request.setRequestBody(body);

        var response = request.execute();
        var status = response.getStatusCode();
        var responseBody = response.getBody();

        if (status < 200 || status >= 300) {
            gs.error('[HcConnectorEcsLifecycleAction] ' + action + ' failed for CI ' + ciSysId +
                ' (server ' + ctx.nativeKey + '): ' + status + ' - ' + responseBody);
            this._insertActionLog(ciSysId, action, paramsStr, null, 'fail', 'HTTP ' + status + ' - ' + responseBody);
            throw new Error('ECS ' + action + ' action failed: HTTP ' + status + ' - ' + responseBody);
        }

        gs.info('[HcConnectorEcsLifecycleAction] ' + action + ' issued for CI ' + ciSysId +
            ' (server ' + ctx.nativeKey + '): HTTP ' + status + ' - ' + responseBody);

        var jobId = this._extractJobId(responseBody);
        if (!jobId) {
            this._insertActionLog(ciSysId, action, paramsStr, null, 'requested', null);
            return { status: status, body: responseBody, jobId: null, jobStatus: null };
        }

        var jobResult = this._fetchJobStatus(disco, host, ctx.region.project_id, jobId);
        if (jobResult && jobResult.status === 'FAIL') {
            gs.error('[HcConnectorEcsLifecycleAction] ' + action + ' job ' + jobId + ' FAILED for CI ' + ciSysId +
                ': ' + JSON.stringify(jobResult));
            var failMsg = 'ECS ' + action + ' action was accepted (HTTP ' + status + ') but job ' + jobId +
                ' failed: ' + (jobResult.fail_reason || jobResult.message || JSON.stringify(jobResult));
            this._insertActionLog(ciSysId, action, paramsStr, jobId, 'fail', failMsg);
            throw new Error(failMsg);
        }
        if (jobResult && jobResult.status === 'SUCCESS') {
            gs.info('[HcConnectorEcsLifecycleAction] ' + action + ' job ' + jobId + ' SUCCESS for CI ' + ciSysId);
            this._insertActionLog(ciSysId, action, paramsStr, jobId, 'success', null);
            return { status: status, body: responseBody, jobId: jobId, jobStatus: 'SUCCESS' };
        }

        var observedStatus = jobResult ? jobResult.status : 'UNKNOWN';
        gs.info('[HcConnectorEcsLifecycleAction] ' + action + ' job ' + jobId + ' for CI ' + ciSysId +
            ' not yet terminal at first check (status=' + observedStatus + ') - not treated as an error, call ' +
            'checkJobStatus(ciSysId, jobId) again later to see if it finished');
        this._insertActionLog(ciSysId, action, paramsStr, jobId, 'running', null);
        return { status: status, body: responseBody, jobId: jobId, jobStatus: observedStatus };
    },

    // ------------------------------------------------------------------
    // Resize - same account/region/credential resolution and signing as
    // performAction() above, but a different Huawei endpoint (per-server,
    // not batch) and a different request-body shape. See this file's header
    // comment for the SHUTOFF prerequisite and why it isn't pre-checked here.
    // @param ciSysId - cmdb_ci_vm_instance sys_id
    // @param flavorRef - target Huawei flavor ID (e.g. "s6.large.2")
    // @param opts - { dryRun: boolean }
    // @returns same {status, body, jobId, jobStatus} shape as performAction()
    // ------------------------------------------------------------------
    performResize: function(ciSysId, flavorRef, opts) {
        var ctx = this._resolveContext(ciSysId);
        if (!ctx) {
            throw new Error('CI ' + ciSysId + ' has no active HC Resource Sync State row for resource_type=ecs - not managed by this connector');
        }
        if (!flavorRef) {
            throw new Error('flavorRef is required');
        }

        var provider = createCredentialProvider(ctx.account.auth_mode, {
            propertyReader: function(name) { return gs.getProperty(gs.getCurrentScopeName() + '.' + name); },
            accountId: ctx.account.account_id
        });
        var credentials = provider.getCredentials();

        var disco = new HuaweiECSDiscovery({
            region: ctx.region.region,
            projectId: ctx.region.project_id,
            accessKey: credentials.accessKey,
            secretKey: credentials.secretKey
        });

        var host = 'ecs.' + ctx.region.region + '.myhuaweicloud.com';
        var pathname = '/v1/' + ctx.region.project_id + '/cloudservers/' + ctx.nativeKey + '/resize';
        var body = JSON.stringify(this._buildResizeRequestBody(flavorRef, opts));

        var signed = disco._sign({ method: 'POST', pathname: pathname, host: host, body: body });

        var request = new sn_ws.RESTMessageV2();
        request.setHttpMethod('POST');
        request.setEndpoint('https://' + host + pathname);
        request.setRequestHeader('Content-Type', signed['Content-Type']);
        request.setRequestHeader('X-Sdk-Date', signed['X-Sdk-Date']);
        request.setRequestHeader('Authorization', signed['Authorization']);
        request.setRequestHeader('host', host);
        request.setRequestBody(body);

        var response = request.execute();
        var status = response.getStatusCode();
        var responseBody = response.getBody();

        if (status < 200 || status >= 300) {
            gs.error('[HcConnectorEcsLifecycleAction] resize failed for CI ' + ciSysId +
                ' (server ' + ctx.nativeKey + ' -> ' + flavorRef + '): ' + status + ' - ' + responseBody);
            this._insertActionLog(ciSysId, 'resize', flavorRef, null, 'fail', 'HTTP ' + status + ' - ' + responseBody);
            throw new Error('ECS resize action failed: HTTP ' + status + ' - ' + responseBody);
        }

        gs.info('[HcConnectorEcsLifecycleAction] resize issued for CI ' + ciSysId +
            ' (server ' + ctx.nativeKey + ' -> ' + flavorRef + '): HTTP ' + status + ' - ' + responseBody);

        var jobId = this._extractJobId(responseBody);
        if (!jobId) {
            this._insertActionLog(ciSysId, 'resize', flavorRef, null, 'requested', null);
            return { status: status, body: responseBody, jobId: null, jobStatus: null };
        }

        var jobResult = this._fetchJobStatus(disco, host, ctx.region.project_id, jobId);
        if (jobResult && jobResult.status === 'FAIL') {
            gs.error('[HcConnectorEcsLifecycleAction] resize job ' + jobId + ' FAILED for CI ' + ciSysId +
                ': ' + JSON.stringify(jobResult));
            var resizeFailMsg = 'ECS resize action was accepted (HTTP ' + status + ') but job ' + jobId +
                ' failed: ' + (jobResult.fail_reason || jobResult.message || JSON.stringify(jobResult));
            this._insertActionLog(ciSysId, 'resize', flavorRef, jobId, 'fail', resizeFailMsg);
            throw new Error(resizeFailMsg);
        }
        if (jobResult && jobResult.status === 'SUCCESS') {
            gs.info('[HcConnectorEcsLifecycleAction] resize job ' + jobId + ' SUCCESS for CI ' + ciSysId);
            this._insertActionLog(ciSysId, 'resize', flavorRef, jobId, 'success', null);
            return { status: status, body: responseBody, jobId: jobId, jobStatus: 'SUCCESS' };
        }

        var observedStatus = jobResult ? jobResult.status : 'UNKNOWN';
        gs.info('[HcConnectorEcsLifecycleAction] resize job ' + jobId + ' for CI ' + ciSysId +
            ' not yet terminal at first check (status=' + observedStatus + ') - not treated as an error, call ' +
            'checkJobStatus(ciSysId, jobId) again later to see if it finished');
        this._insertActionLog(ciSysId, 'resize', flavorRef, jobId, 'running', null);
        return { status: status, body: responseBody, jobId: jobId, jobStatus: observedStatus };
    },

    // ------------------------------------------------------------------
    // Attach an EVS disk to this ECS instance. Same account/region/
    // credential resolution and signing as performAction()/performResize()
    // above, a different Huawei endpoint and request-body shape.
    // @param ciSysId - cmdb_ci_vm_instance sys_id (the target server)
    // @param volumeId - Huawei EVS disk UUID to attach
    // @param opts - { device: string, dryRun: boolean }
    // @returns same {status, body, jobId, jobStatus} shape as performAction()
    // ------------------------------------------------------------------
    performAttach: function(ciSysId, volumeId, opts) {
        var ctx = this._resolveContext(ciSysId);
        if (!ctx) {
            throw new Error('CI ' + ciSysId + ' has no active HC Resource Sync State row for resource_type=ecs - not managed by this connector');
        }
        if (!volumeId) {
            throw new Error('volumeId is required');
        }

        var provider = createCredentialProvider(ctx.account.auth_mode, {
            propertyReader: function(name) { return gs.getProperty(gs.getCurrentScopeName() + '.' + name); },
            accountId: ctx.account.account_id
        });
        var credentials = provider.getCredentials();

        var disco = new HuaweiECSDiscovery({
            region: ctx.region.region,
            projectId: ctx.region.project_id,
            accessKey: credentials.accessKey,
            secretKey: credentials.secretKey
        });

        var host = 'ecs.' + ctx.region.region + '.myhuaweicloud.com';
        var pathname = '/v1/' + ctx.region.project_id + '/cloudservers/' + ctx.nativeKey + '/attachvolume';
        var body = JSON.stringify(this._buildAttachRequestBody(volumeId, opts));

        var signed = disco._sign({ method: 'POST', pathname: pathname, host: host, body: body });

        var request = new sn_ws.RESTMessageV2();
        request.setHttpMethod('POST');
        request.setEndpoint('https://' + host + pathname);
        request.setRequestHeader('Content-Type', signed['Content-Type']);
        request.setRequestHeader('X-Sdk-Date', signed['X-Sdk-Date']);
        request.setRequestHeader('Authorization', signed['Authorization']);
        request.setRequestHeader('host', host);
        request.setRequestBody(body);

        var response = request.execute();
        var status = response.getStatusCode();
        var responseBody = response.getBody();

        if (status < 200 || status >= 300) {
            gs.error('[HcConnectorEcsLifecycleAction] attach failed for CI ' + ciSysId +
                ' (server ' + ctx.nativeKey + ' <- volume ' + volumeId + '): ' + status + ' - ' + responseBody);
            this._insertActionLog(ciSysId, 'attach', volumeId, null, 'fail', 'HTTP ' + status + ' - ' + responseBody);
            throw new Error('ECS attach action failed: HTTP ' + status + ' - ' + responseBody);
        }

        gs.info('[HcConnectorEcsLifecycleAction] attach issued for CI ' + ciSysId +
            ' (server ' + ctx.nativeKey + ' <- volume ' + volumeId + '): HTTP ' + status + ' - ' + responseBody);

        var jobId = this._extractJobId(responseBody);
        if (!jobId) {
            this._insertActionLog(ciSysId, 'attach', volumeId, null, 'requested', null);
            return { status: status, body: responseBody, jobId: null, jobStatus: null };
        }

        var jobResult = this._fetchJobStatus(disco, host, ctx.region.project_id, jobId);
        if (jobResult && jobResult.status === 'FAIL') {
            gs.error('[HcConnectorEcsLifecycleAction] attach job ' + jobId + ' FAILED for CI ' + ciSysId +
                ': ' + JSON.stringify(jobResult));
            var attachFailMsg = 'ECS attach action was accepted (HTTP ' + status + ') but job ' + jobId +
                ' failed: ' + (jobResult.fail_reason || jobResult.message || JSON.stringify(jobResult));
            this._insertActionLog(ciSysId, 'attach', volumeId, jobId, 'fail', attachFailMsg);
            throw new Error(attachFailMsg);
        }
        if (jobResult && jobResult.status === 'SUCCESS') {
            gs.info('[HcConnectorEcsLifecycleAction] attach job ' + jobId + ' SUCCESS for CI ' + ciSysId);
            this._insertActionLog(ciSysId, 'attach', volumeId, jobId, 'success', null);
            return { status: status, body: responseBody, jobId: jobId, jobStatus: 'SUCCESS' };
        }

        var attachObservedStatus = jobResult ? jobResult.status : 'UNKNOWN';
        gs.info('[HcConnectorEcsLifecycleAction] attach job ' + jobId + ' for CI ' + ciSysId +
            ' not yet terminal at first check (status=' + attachObservedStatus + ') - not treated as an error, call ' +
            'checkJobStatus(ciSysId, jobId) again later to see if it finished');
        this._insertActionLog(ciSysId, 'attach', volumeId, jobId, 'running', null);
        return { status: status, body: responseBody, jobId: jobId, jobStatus: attachObservedStatus };
    },

    // ------------------------------------------------------------------
    // Detach an EVS disk from this ECS instance. No request body at all
    // (see this file's header comment) - just an optional ?delete_flag=1
    // query param for a forced detach, included in the signed queryParams
    // too (Huawei's signature covers the actual query string sent).
    // @param ciSysId - cmdb_ci_vm_instance sys_id (the target server)
    // @param volumeId - Huawei EVS disk UUID to detach
    // @param opts - { force: boolean }
    // @returns same {status, body, jobId, jobStatus} shape as performAction()
    // ------------------------------------------------------------------
    performDetach: function(ciSysId, volumeId, opts) {
        var ctx = this._resolveContext(ciSysId);
        if (!ctx) {
            throw new Error('CI ' + ciSysId + ' has no active HC Resource Sync State row for resource_type=ecs - not managed by this connector');
        }
        if (!volumeId) {
            throw new Error('volumeId is required');
        }
        opts = opts || {};

        var provider = createCredentialProvider(ctx.account.auth_mode, {
            propertyReader: function(name) { return gs.getProperty(gs.getCurrentScopeName() + '.' + name); },
            accountId: ctx.account.account_id
        });
        var credentials = provider.getCredentials();

        var disco = new HuaweiECSDiscovery({
            region: ctx.region.region,
            projectId: ctx.region.project_id,
            accessKey: credentials.accessKey,
            secretKey: credentials.secretKey
        });

        var host = 'ecs.' + ctx.region.region + '.myhuaweicloud.com';
        var pathname = '/v1/' + ctx.region.project_id + '/cloudservers/' + ctx.nativeKey + '/detachvolume/' + volumeId;
        var queryParams = opts.force ? { delete_flag: '1' } : {};
        var queryString = opts.force ? '?delete_flag=1' : '';

        var signed = disco._sign({ method: 'DELETE', pathname: pathname, host: host, queryParams: queryParams });

        var request = new sn_ws.RESTMessageV2();
        request.setHttpMethod('DELETE');
        request.setEndpoint('https://' + host + pathname + queryString);
        request.setRequestHeader('Content-Type', signed['Content-Type']);
        request.setRequestHeader('X-Sdk-Date', signed['X-Sdk-Date']);
        request.setRequestHeader('Authorization', signed['Authorization']);
        request.setRequestHeader('host', host);

        var response = request.execute();
        var status = response.getStatusCode();
        var responseBody = response.getBody();

        if (status < 200 || status >= 300) {
            gs.error('[HcConnectorEcsLifecycleAction] detach failed for CI ' + ciSysId +
                ' (server ' + ctx.nativeKey + ' -> volume ' + volumeId + '): ' + status + ' - ' + responseBody);
            this._insertActionLog(ciSysId, 'detach', volumeId, null, 'fail', 'HTTP ' + status + ' - ' + responseBody);
            throw new Error('ECS detach action failed: HTTP ' + status + ' - ' + responseBody);
        }

        gs.info('[HcConnectorEcsLifecycleAction] detach issued for CI ' + ciSysId +
            ' (server ' + ctx.nativeKey + ' -> volume ' + volumeId + '): HTTP ' + status + ' - ' + responseBody);

        var jobId = this._extractJobId(responseBody);
        if (!jobId) {
            this._insertActionLog(ciSysId, 'detach', volumeId, null, 'requested', null);
            return { status: status, body: responseBody, jobId: null, jobStatus: null };
        }

        var jobResult = this._fetchJobStatus(disco, host, ctx.region.project_id, jobId);
        if (jobResult && jobResult.status === 'FAIL') {
            gs.error('[HcConnectorEcsLifecycleAction] detach job ' + jobId + ' FAILED for CI ' + ciSysId +
                ': ' + JSON.stringify(jobResult));
            var detachFailMsg = 'ECS detach action was accepted (HTTP ' + status + ') but job ' + jobId +
                ' failed: ' + (jobResult.fail_reason || jobResult.message || JSON.stringify(jobResult));
            this._insertActionLog(ciSysId, 'detach', volumeId, jobId, 'fail', detachFailMsg);
            throw new Error(detachFailMsg);
        }
        if (jobResult && jobResult.status === 'SUCCESS') {
            gs.info('[HcConnectorEcsLifecycleAction] detach job ' + jobId + ' SUCCESS for CI ' + ciSysId);
            this._insertActionLog(ciSysId, 'detach', volumeId, jobId, 'success', null);
            return { status: status, body: responseBody, jobId: jobId, jobStatus: 'SUCCESS' };
        }

        var detachObservedStatus = jobResult ? jobResult.status : 'UNKNOWN';
        gs.info('[HcConnectorEcsLifecycleAction] detach job ' + jobId + ' for CI ' + ciSysId +
            ' not yet terminal at first check (status=' + detachObservedStatus + ') - not treated as an error, call ' +
            'checkJobStatus(ciSysId, jobId) again later to see if it finished');
        this._insertActionLog(ciSysId, 'detach', volumeId, jobId, 'running', null);
        return { status: status, body: responseBody, jobId: jobId, jobStatus: detachObservedStatus };
    },

    // ------------------------------------------------------------------
    // Public: check a previously-issued job's current status again, e.g.
    // from a Background Script, since performAction() only checks once
    // (see this file's header comment for why - gs.sleep() is fenced in
    // this scope, so a wait-and-poll loop isn't viable inside the same
    // transaction). Also updates the matching HC Day-2 Action Log row (via
    // _updateActionLogByJobId()) so a later re-check - whether ad hoc or
    // from pollPendingActionLogs() below - keeps that row's status current.
    // @param ciSysId - the same CI passed to performAction()
    // @param jobId - from performAction()'s returned {jobId}
    // @returns the parsed job status body, or null if the check itself failed
    // ------------------------------------------------------------------
    checkJobStatus: function(ciSysId, jobId) {
        var ctx = this._resolveContext(ciSysId);
        if (!ctx) {
            throw new Error('CI ' + ciSysId + ' has no active HC Resource Sync State row for resource_type=ecs - not managed by this connector');
        }

        var provider = createCredentialProvider(ctx.account.auth_mode, {
            propertyReader: function(name) { return gs.getProperty(gs.getCurrentScopeName() + '.' + name); },
            accountId: ctx.account.account_id
        });
        var credentials = provider.getCredentials();

        var disco = new HuaweiECSDiscovery({
            region: ctx.region.region,
            projectId: ctx.region.project_id,
            accessKey: credentials.accessKey,
            secretKey: credentials.secretKey
        });

        var host = 'ecs.' + ctx.region.region + '.myhuaweicloud.com';
        var jobResult = this._fetchJobStatus(disco, host, ctx.region.project_id, jobId);
        if (jobResult) {
            if (jobResult.status === 'SUCCESS') {
                this._updateActionLogByJobId(jobId, 'success', null);
            } else if (jobResult.status === 'FAIL') {
                this._updateActionLogByJobId(jobId, 'fail', jobResult.fail_reason || jobResult.message || JSON.stringify(jobResult));
            } else {
                this._updateActionLogByJobId(jobId, 'running', null);
            }
        }
        return jobResult;
    },

    // ------------------------------------------------------------------
    // Public: re-checks every HC Day-2 Action Log row still in 'requested'
    // or 'running' status. Called by scheduled-jobs/hc_connector_day2_job_poller.js
    // on a schedule - the real mechanism (not a UI-session wait-and-poll
    // loop, since gs.sleep() is fenced here) that eventually resolves a
    // job's log row to 'success'/'fail' even if nobody ever comes back to
    // manually check it. Reuses checkJobStatus() so the update logic only
    // lives in one place.
    // ------------------------------------------------------------------
    pollPendingActionLogs: function() {
        var gr = new GlideRecord(this.ACTION_LOG_TABLE);
        gr.addQuery('status', 'IN', 'requested,running');
        gr.addNotNullQuery('job_id');
        gr.query();
        var checked = 0;
        while (gr.next()) {
            var ciSysId = gr.getValue('ci');
            var jobId = gr.getValue('job_id');
            try {
                this.checkJobStatus(ciSysId, jobId);
                checked++;
            } catch (ex) {
                gs.warn('[HcConnectorEcsLifecycleAction] pollPendingActionLogs: checkJobStatus failed for job ' +
                    jobId + ' (CI ' + ciSysId + '): ' + ex.message);
            }
        }
        gs.info('[HcConnectorEcsLifecycleAction] pollPendingActionLogs checked ' + checked + ' pending job(s)');
    },

    // ------------------------------------------------------------------
    // HC Day-2 Action Log writes. _insertActionLog() is called once per
    // performX() invocation, at whichever exit point it reached (HTTP
    // failure / job FAIL / job SUCCESS / job still running / no job_id at
    // all) - always a fresh row, since each button click is a new,
    // independent action request. _updateActionLogByJobId() is called from
    // checkJobStatus() (ad hoc or via pollPendingActionLogs()) to move an
    // existing row to a terminal status found on a later check - a no-op if
    // no row matches that job_id (mirrors this file's existing
    // _recordRegionError()-style get-or-noop pattern, not a hard failure).
    // ------------------------------------------------------------------
    _insertActionLog: function(ciSysId, action, params, jobId, status, errorMessage) {
        var gr = new GlideRecord(this.ACTION_LOG_TABLE);
        gr.initialize();
        gr.ci = ciSysId;
        gr.action = action;
        if (params) gr.params = params;
        if (jobId) gr.job_id = jobId;
        gr.status = status;
        if (errorMessage) gr.error_message = errorMessage;
        gr.requested_by = gs.getUserID();
        gr.requested_at = new GlideDateTime();
        gr.updated_at = new GlideDateTime();
        gr.insert();
    },

    _updateActionLogByJobId: function(jobId, status, errorMessage) {
        if (!jobId) return;
        var gr = new GlideRecord(this.ACTION_LOG_TABLE);
        gr.addQuery('job_id', jobId);
        gr.query();
        if (!gr.next()) return;
        gr.status = status;
        if (errorMessage) gr.error_message = errorMessage;
        gr.updated_at = new GlideDateTime();
        gr.update();
    },

    // ------------------------------------------------------------------
    // Single, non-blocking job-status check - Huawei's async job-tracking
    // endpoint, same host as the action itself. No loop, no gs.sleep()
    // (fenced in this scope - see this file's header comment). Returns the
    // parsed job body (whatever status it currently reports, terminal or
    // not), or null if the HTTP call itself failed.
    // ------------------------------------------------------------------
    _fetchJobStatus: function(disco, host, projectId, jobId) {
        var pathname = '/v1/' + projectId + '/jobs/' + jobId;
        try {
            var signed = disco._sign({ method: 'GET', pathname: pathname, host: host });

            var request = new sn_ws.RESTMessageV2();
            request.setHttpMethod('GET');
            request.setEndpoint('https://' + host + pathname);
            request.setRequestHeader('Content-Type', signed['Content-Type']);
            request.setRequestHeader('X-Sdk-Date', signed['X-Sdk-Date']);
            request.setRequestHeader('Authorization', signed['Authorization']);
            request.setRequestHeader('host', host);

            var response = request.execute();
            var status = response.getStatusCode();
            var body = response.getBody();

            gs.info('[HcConnectorEcsLifecycleAction] job ' + jobId + ' status check: HTTP ' + status + ' - ' + body);

            if (status == 200) return JSON.parse(body);
            gs.warn('[HcConnectorEcsLifecycleAction] job ' + jobId + ' status check got HTTP ' + status);
            return null;
        } catch (ex) {
            gs.warn('[HcConnectorEcsLifecycleAction] job ' + jobId + ' status check exception: ' + ex.message);
            return null;
        }
    },

    _extractJobId: function(responseBody) {
        try {
            var parsed = JSON.parse(responseBody);
            return (parsed && parsed.job_id) || null;
        } catch (ex) {
            return null;
        }
    },

    // ------------------------------------------------------------------
    // Resolve which HC Cloud Account/HC Cloud Region a CI belongs to via
    // HC Resource Sync State - the same join every sync orchestrator
    // writes, read here instead of written.
    // ------------------------------------------------------------------
    _resolveContext: function(ciSysId) {
        var stateGr = new GlideRecord(this.SYNC_STATE_TABLE);
        stateGr.addQuery('ci', ciSysId);
        stateGr.addQuery('resource_type', this.RESOURCE_TYPE);
        stateGr.addQuery('status', '!=', 'retired');
        stateGr.query();
        if (!stateGr.next()) return null;

        var nativeKey = stateGr.getValue('native_key');

        var accountGr = new GlideRecord(this.ACCOUNT_TABLE);
        if (!accountGr.get(stateGr.getValue('account'))) return null;

        var regionGr = new GlideRecord(this.REGION_TABLE);
        if (!regionGr.get(stateGr.getValue('region'))) return null;

        return {
            nativeKey: nativeKey,
            account: { sys_id: accountGr.getUniqueValue(), account_id: accountGr.getValue('account_id'), auth_mode: accountGr.getValue('auth_mode') },
            region: { sys_id: regionGr.getUniqueValue(), region: regionGr.getValue('region'), project_id: regionGr.getValue('project_id') }
        };
    },

    // ------------------------------------------------------------------
    // Mirrors lib/ecsLifecycleAction.js's buildActionRequestBody() inline.
    // Keep in sync - covered by check-mirror-drift.js's ninth PAIRS entry.
    // ------------------------------------------------------------------
    _buildActionRequestBody: function(action, serverId, opts) {
        var VALID_ACTIONS = ['start', 'stop', 'reboot'];
        if (VALID_ACTIONS.indexOf(action) === -1) {
            throw new Error('Unknown ECS lifecycle action: ' + action + ' (must be one of ' + VALID_ACTIONS.join(', ') + ')');
        }
        if (!serverId) {
            throw new Error('serverId is required');
        }
        opts = opts || {};
        var mode = opts.hard ? 'HARD' : 'SOFT';
        var servers = [{ id: serverId }];

        if (action === 'start') {
            return { 'os-start': { servers: servers } };
        }
        if (action === 'stop') {
            return { 'os-stop': { servers: servers, type: mode } };
        }
        return { reboot: { type: mode, servers: servers } };
    },

    // ------------------------------------------------------------------
    // Mirrors lib/ecsLifecycleAction.js's buildResizeRequestBody() inline.
    // Keep in sync - covered by check-mirror-drift.js's ninth PAIRS entry.
    // ------------------------------------------------------------------
    _buildResizeRequestBody: function(flavorRef, opts) {
        if (!flavorRef) {
            throw new Error('flavorRef is required');
        }
        opts = opts || {};
        return { resize: { flavorRef: flavorRef }, dry_run: !!opts.dryRun };
    },

    // ------------------------------------------------------------------
    // Mirrors lib/ecsLifecycleAction.js's buildAttachRequestBody() inline.
    // Keep in sync - covered by check-mirror-drift.js's ninth PAIRS entry.
    // No corresponding mirror for detach - it has no request body (see this
    // file's header comment).
    // ------------------------------------------------------------------
    _buildAttachRequestBody: function(volumeId, opts) {
        if (!volumeId) {
            throw new Error('volumeId is required');
        }
        opts = opts || {};
        var volumeAttachment = { volumeId: volumeId };
        if (opts.device) {
            volumeAttachment.device = opts.device;
        }
        return { volumeAttachment: volumeAttachment, dry_run: !!opts.dryRun };
    },

    type: 'HcConnectorEcsLifecycleAction'
};
