// Script Include: HcConnectorEcsSync
// HAND-WRITTEN TEMPLATE - do not paste this file directly into ServiceNow.
// The deployable version is generated by
// scripts/build-script-include.js, which inlines lib/credentialProvider.js,
// lib/resourceLifecycle.js, lib/compositeKey.js, lib/discoveryRunTracker.js,
// and lib/syncStatePlanner.js (module.exports stripped) at the marker below,
// producing docs/generated/HcConnectorEcsSync.generated.js - paste THAT.
//
// Multi-account/region ECS sync orchestrator (HC ITOM Connector Phase 2A).
// For every active HC Cloud Region under every active HC Cloud Account:
//   1. resolve credentials (createCredentialProvider, from HC Cloud
//      Account.auth_mode)
//   2. construct a HuaweiECSDiscovery with explicit config (its existing
//      fetch/sign/reconcile logic is UNCHANGED - see
//      servicenow/discovery/HuaweiECSDiscovery.js)
//   3. fetch, then reconcile via IRE (also unchanged)
//   4. upsert HC Resource Sync State (never a blind insert - always via
//      planSyncStateUpdates, which looks at what's already there)
//   5. run the retirement pass - but ONLY if steps 3-4 both succeeded; a
//      fetch or reconcile failure skips straight to recording the error and
//      moving to the next region, never reaching the retirement logic. This
//      is what makes "an incomplete sync can never retire a resource" a
//      structural guarantee instead of a hope.
// One account/region's failure is caught and logged without stopping the
// loop for the others.
//
// Resource-type-specific on purpose: VPC/EVS/EIP (Phase 2B) get their own
// orchestrator first, generalized into a shared one once a second resource
// type makes the real common shape visible - not guessed at now.

// __HC_CONNECTOR_INLINED_LIB__

var HcConnectorEcsSync = Class.create();
HcConnectorEcsSync.prototype = {
    initialize: function() {
        this.SCOPE = 'x_2021019_huawei_0';
        this.ACCOUNT_TABLE = this.SCOPE + '_hc_cloud_account';
        this.REGION_TABLE = this.SCOPE + '_hc_cloud_region';
        this.RUN_TABLE = this.SCOPE + '_hc_discovery_run';
        this.SYNC_STATE_TABLE = this.SCOPE + '_hc_resource_sync_state';
        this.CONFIG_TABLE = this.SCOPE + '_hc_connector_config';
        this.RESOURCE_TYPE = 'ecs';
    },

    // ------------------------------------------------------------------
    // Entry point
    // ------------------------------------------------------------------
    runAll: function() {
        var self = this;
        var accounts = this._getActiveAccounts();
        gs.info('[HcConnectorEcsSync] starting run across ' + accounts.length + ' active account(s)');
        accounts.forEach(function(account) {
            var regions = self._getActiveRegions(account.sys_id);
            regions.forEach(function(region) {
                try {
                    self._runForAccountRegion(account, region);
                } catch (ex) {
                    // Last-resort catch: _runForAccountRegion already isolates fetch/reconcile
                    // failures internally, so reaching here means something unexpected (e.g. a
                    // GlideRecord error building the run/region context itself) - still must not
                    // stop the loop for the remaining accounts/regions.
                    gs.error('[HcConnectorEcsSync] unexpected failure for account=' + account.account_id +
                        ' region=' + region.region + ': ' + ex.message);
                    self._recordRegionError(region.sys_id, ex.message);
                }
            });
        });
        gs.info('[HcConnectorEcsSync] run complete');
    },

    _runForAccountRegion: function(account, region) {
        var startedAtMs = new Date().getTime();
        var runFields = startRun({
            accountSysId: account.sys_id,
            regionSysId: region.sys_id,
            resourceType: this.RESOURCE_TYPE,
            correlationId: account.account_id + ':' + region.region,
            traceId: gs.generateGUID(),
            startedAtMs: startedAtMs
        });
        var runRecordSysId = this._insertDiscoveryRun(runFields);

        var fetchResult;
        try {
            fetchResult = this._fetchServers(account, region);
        } catch (fetchEx) {
            gs.error('[HcConnectorEcsSync] fetch failed for account=' + account.account_id +
                ' region=' + region.region + ': ' + fetchEx.message);
            this._recordRegionError(region.sys_id, fetchEx.message);
            this._updateDiscoveryRun(runRecordSysId, finishRun(runFields,
                { successCount: 0, failCount: 0, errorSummary: fetchEx.message, endedAtMs: new Date().getTime() }));
            return; // structural guarantee: retirement below is unreachable on fetch failure
        }

        var reconcileResult;
        try {
            reconcileResult = this._reconcileAndUpsert(account, region, fetchResult.servers, fetchResult.disco);
        } catch (reconcileEx) {
            gs.error('[HcConnectorEcsSync] reconcile failed for account=' + account.account_id +
                ' region=' + region.region + ': ' + reconcileEx.message);
            this._recordRegionError(region.sys_id, reconcileEx.message);
            this._updateDiscoveryRun(runRecordSysId, finishRun(runFields,
                { successCount: 0, failCount: fetchResult.servers.length, errorSummary: reconcileEx.message, endedAtMs: new Date().getTime() }));
            return; // also skip retirement - we don't know which CIs actually got created
        }

        this._updateDiscoveryRun(runRecordSysId, finishRun(runFields, {
            successCount: reconcileResult.summary.insertCount + reconcileResult.summary.refreshCount,
            failCount: 0,
            endedAtMs: new Date().getTime()
        }));
        this._recordRegionSuccess(region.sys_id);
        gs.info('[HcConnectorEcsSync] account=' + account.account_id + ' region=' + region.region +
            ' done: ' + JSON.stringify(reconcileResult.summary));
    },

    // ------------------------------------------------------------------
    // Fetch (delegates to the unchanged HuaweiECSDiscovery)
    // ------------------------------------------------------------------
    _fetchServers: function(account, region) {
        var provider = createCredentialProvider(account.auth_mode, {
            propertyReader: function(name) { return gs.getProperty(gs.getCurrentScopeName() + '.' + name); },
            accountId: account.account_id
        });
        var credentials = provider.getCredentials(); // throws NotImplemented for 'agency' - correctly surfaces as a fetch failure above

        var disco = new HuaweiECSDiscovery({
            region: region.region,
            projectId: region.project_id,
            pageLimit: this._getConnectorConfigValue('ecs_page_limit', 100),
            maxRetryAttempts: this._getConnectorConfigValue('ecs_max_retry_attempts', 3),
            accessKey: credentials.accessKey,
            secretKey: credentials.secretKey
        });

        var servers = disco.fetchECSInstances(); // throws on a page failure - see HuaweiECSDiscovery.js
        return { disco: disco, servers: servers };
    },

    // ------------------------------------------------------------------
    // Reconcile (delegates to the unchanged HuaweiECSDiscovery.reconcileCIs)
    // + upsert HC Resource Sync State + retirement
    // ------------------------------------------------------------------
    _reconcileAndUpsert: function(account, region, servers, disco) {
        var self = this;

        // Zero servers this run is a valid, expected state (e.g. the
        // account's only tracked instance was destroyed outside this
        // project) - NOT the same thing as reconcileCIs() failing on a
        // non-empty list. reconcileCIs([]) returns undefined by its own
        // design (nothing to reconcile, see HuaweiECSDiscovery.js), and
        // that undefined return must not be treated as an IRE failure here,
        // or the retirement pass below never runs and a fully-emptied
        // account can never have its stale CIs retired - a real gap found
        // via real-PDI testing (an account dropping to zero ECS instances
        // for the first time), not a hypothetical. Skip the reconcileCIs()
        // call entirely when there's nothing to reconcile and fall through
        // to sync-state planning with an empty seenRecords set, so existing
        // rows correctly transition toward retirement.
        if (servers.length > 0) {
            // Reuses the SAME disco instance _fetchServers already built (passed in as a
            // parameter), rather than constructing a throwaway one here - reconcileCIs() now
            // makes its own real HTTP call to Huawei's flavor-detail endpoint (for cpus/memory
            // CI fields, see HuaweiECSDiscovery.js), so it genuinely needs the real
            // accessKey/secretKey/projectId this account/region resolved, not just `this.region`.
            // A throwaway credential-less instance was safe when reconcileCIs() only needed
            // `this.region` for the placeholder virtualization-server name - that's no longer
            // true, so reusing the real instance is a correctness fix, not just tidiness.
            var result = disco.reconcileCIs(servers);

            // reconcileCIs catches its own exceptions internally and returns undefined on
            // failure rather than rethrowing (see HuaweiECSDiscovery.js) - this is where that
            // silent failure gets converted into a real thrown error our caller can act on.
            if (!result) {
                throw new Error('reconcileCIs returned no result - the IRE call likely failed, see the prior gs.error log from HuaweiECSDiscovery');
            }
            if (result.hasError) {
                // Conservative for Phase 2A: treat any reported IRE error as a failure for the
                // whole batch rather than guessing which items succeeded from the result shape.
                // errorCount is per-item/per-relation in the real IRE response shape, not a
                // top-level field (confirmed via Phase 2B real-PDI testing) - sum it up for a
                // useful count.
                var totalErrors = (result.items || []).reduce(function(sum, item) { return sum + (item.errorCount || 0); }, 0) +
                    (result.relations || []).reduce(function(sum, rel) { return sum + (rel.errorCount || 0); }, 0);
                throw new Error('IRE reconciliation reported errors (errorCount=' + totalErrors + ') - see the prior gs.info log for the full result');
            }
        }

        var seenRecords = servers.map(function(s) {
            return { native_key: s.id, ci: self._lookupCiByCorrelationId(s.id) };
        });

        var existingRows = this._getExistingSyncStateRows(account.sys_id, region.sys_id);
        var plan = planSyncStateUpdates(seenRecords, existingRows, {
            computeNextState: computeNextState,
            consecutiveMissThreshold: this._getConsecutiveMissThreshold()
        });

        this._applyInserts(account, region, plan.toInsert);
        this._applyRefreshes(plan.toRefresh);
        this._applyTransitions(plan.toTransition);

        return { plan: plan, summary: summarizePlan(plan) };
    },

    _lookupCiByCorrelationId: function(correlationId) {
        var gr = new GlideRecord('cmdb_ci_vm_instance');
        gr.addQuery('correlation_id', correlationId);
        gr.query();
        if (gr.next()) return gr.getUniqueValue();
        return null;
    },

    // ------------------------------------------------------------------
    // HC Resource Sync State reads/writes
    // ------------------------------------------------------------------
    _getExistingSyncStateRows: function(accountSysId, regionSysId) {
        var results = [];
        var gr = new GlideRecord(this.SYNC_STATE_TABLE);
        gr.addQuery('account', accountSysId);
        gr.addQuery('region', regionSysId);
        gr.addQuery('resource_type', this.RESOURCE_TYPE);
        gr.query();
        while (gr.next()) {
            results.push({
                sys_id: gr.getUniqueValue(),
                native_key: gr.getValue('native_key'),
                status: gr.getValue('status'),
                consecutive_miss_count: parseInt(gr.getValue('consecutive_miss_count'), 10) || 0
            });
        }
        return results;
    },

    _applyInserts: function(account, region, toInsert) {
        var self = this;
        toInsert.forEach(function(entry) {
            var gr = new GlideRecord(self.SYNC_STATE_TABLE);
            gr.initialize();
            gr.account = account.sys_id;
            gr.region = region.sys_id;
            gr.resource_type = self.RESOURCE_TYPE;
            gr.native_key = entry.native_key;
            if (entry.ci) gr.ci = entry.ci;
            gr.last_seen = new GlideDateTime();
            gr.consecutive_miss_count = 0;
            gr.status = 'active';
            gr.insert();
        });
    },

    _applyRefreshes: function(toRefresh) {
        var self = this;
        toRefresh.forEach(function(entry) {
            var gr = new GlideRecord(self.SYNC_STATE_TABLE);
            if (!gr.get(entry.sys_id)) return;
            if (entry.ci) gr.ci = entry.ci;
            gr.last_seen = new GlideDateTime();
            gr.consecutive_miss_count = 0;
            gr.status = 'active';
            gr.update();
        });
    },

    _applyTransitions: function(toTransition) {
        var self = this;
        toTransition.forEach(function(entry) {
            var gr = new GlideRecord(self.SYNC_STATE_TABLE);
            if (!gr.get(entry.sys_id)) return;
            var ciSysId = gr.getValue('ci');
            gr.status = entry.status;
            gr.consecutive_miss_count = entry.consecutive_miss_count;
            gr.update();

            if (entry.justRetired && ciSysId) {
                self._retireCi(ciSysId);
            }
        });
    },

    _retireCi: function(ciSysId) {
        var retiredValue = this._getRetiredInstallStatusValue();
        if (retiredValue == null) {
            gs.warn('[HcConnectorEcsSync] could not resolve cmdb_ci.install_status "Retired" choice value - CI ' +
                ciSysId + ' was retired in HC Resource Sync State but NOT in CMDB, fix manually');
            return;
        }
        var gr = new GlideRecord('cmdb_ci');
        if (!gr.get(ciSysId)) return;
        gr.install_status = retiredValue;
        gr.update();
        gs.info('[HcConnectorEcsSync] retired CI ' + ciSysId);
    },

    // Looked up dynamically rather than hardcoded - install_status choice
    // values are not guaranteed identical across ServiceNow versions/instances
    // (see the same reasoning already applied to discovery_source in
    // servicenow/discovery/README.md - don't guess a magic number, query it).
    _getRetiredInstallStatusValue: function() {
        var gr = new GlideRecord('sys_choice');
        gr.addQuery('name', 'cmdb_ci');
        gr.addQuery('element', 'install_status');
        gr.addQuery('label', 'Retired');
        gr.query();
        if (gr.next()) return gr.getValue('value');
        return null;
    },

    // ------------------------------------------------------------------
    // HC Discovery Run reads/writes
    // ------------------------------------------------------------------
    _insertDiscoveryRun: function(runFields) {
        var snFields = toServiceNowDiscoveryRunFields(runFields);
        var gr = new GlideRecord(this.RUN_TABLE);
        gr.initialize();
        gr.account = snFields.account;
        gr.region = snFields.region;
        gr.resource_type = snFields.resource_type;
        gr.state = snFields.state;
        gr.started = this._msToGlideDateTime(snFields.started);
        gr.success_count = snFields.success_count;
        gr.fail_count = snFields.fail_count;
        gr.correlation_id = snFields.correlation_id;
        gr.trace_id = snFields.trace_id;
        gr.dry_run = snFields.dry_run;
        return gr.insert();
    },

    _updateDiscoveryRun: function(sysId, runFields) {
        var snFields = toServiceNowDiscoveryRunFields(runFields);
        var gr = new GlideRecord(this.RUN_TABLE);
        if (!gr.get(sysId)) return;
        gr.state = snFields.state;
        if (snFields.ended != null) gr.ended = this._msToGlideDateTime(snFields.ended);
        gr.success_count = snFields.success_count;
        gr.fail_count = snFields.fail_count;
        if (snFields.error_summary) gr.error_summary = snFields.error_summary;
        gr.update();
    },

    // Same epoch-millis -> GlideDateTime pattern already proven in
    // servicenow/event-management/webhook-scripted-rest.js.
    _msToGlideDateTime: function(ms) {
        var gdt = new GlideDateTime();
        gdt.setNumericValue(ms);
        return gdt;
    },

    // ------------------------------------------------------------------
    // HC Cloud Account / HC Cloud Region reads + status writes
    // ------------------------------------------------------------------
    _getActiveAccounts: function() {
        var results = [];
        var gr = new GlideRecord(this.ACCOUNT_TABLE);
        gr.addQuery('active', true);
        gr.query();
        while (gr.next()) {
            results.push({
                sys_id: gr.getUniqueValue(),
                account_id: gr.getValue('account_id'),
                auth_mode: gr.getValue('auth_mode')
            });
        }
        return results;
    },

    _getActiveRegions: function(accountSysId) {
        var results = [];
        var gr = new GlideRecord(this.REGION_TABLE);
        gr.addQuery('account', accountSysId);
        gr.addQuery('active', true);
        gr.addQuery('sync_enabled', true);
        gr.query();
        while (gr.next()) {
            results.push({
                sys_id: gr.getUniqueValue(),
                region: gr.getValue('region'),
                project_id: gr.getValue('project_id')
            });
        }
        return results;
    },

    _recordRegionError: function(regionSysId, message) {
        var gr = new GlideRecord(this.REGION_TABLE);
        if (!gr.get(regionSysId)) return;
        gr.last_error = message;
        gr.update();
    },

    _recordRegionSuccess: function(regionSysId) {
        var gr = new GlideRecord(this.REGION_TABLE);
        if (!gr.get(regionSysId)) return;
        gr.last_success = new GlideDateTime();
        gr.last_error = '';
        gr.update();
    },

    // ------------------------------------------------------------------
    // HC Connector Config reads
    // ------------------------------------------------------------------
    _getConnectorConfigValue: function(key, defaultValue) {
        var gr = new GlideRecord(this.CONFIG_TABLE);
        gr.addQuery('key', key);
        gr.query();
        if (gr.next()) return gr.getValue('value');
        return defaultValue;
    },

    _getConsecutiveMissThreshold: function() {
        var val = this._getConnectorConfigValue('consecutive_miss_threshold', null);
        if (val == null) return undefined; // let resourceLifecycle's own default apply
        var parsed = parseInt(val, 10);
        return isNaN(parsed) ? undefined : parsed;
    },

    type: 'HcConnectorEcsSync'
};
