// Script Include: HcConnectorEcsLifecycleAction
// HAND-WRITTEN TEMPLATE - do not paste this file directly into ServiceNow.
// The deployable version is generated by scripts/build-script-include.js,
// which inlines lib/credentialProvider.js (module.exports stripped) at the
// marker below, producing
// docs/generated/HcConnectorEcsLifecycleAction.generated.js - paste THAT.
// A real-PDI test with this file pasted as-is failed with "createProvider
// is not defined" - createCredentialProvider() is a bare function, not a
// Class.create() class, so it's only visible within whichever ONE Script
// Include file it's physically concatenated into (same reason
// HcConnectorEcsSync.js needed this same treatment) - it does not become
// globally available just because some other Script Include happened to
// load it first.
//
// HC ITOM Connector - Day-2 operations, first slice (start/stop/reboot for
// ECS instances). Everything discovered so far only ever READS the cloud
// account; this is the first artifact in this project that WRITES to it.
//
// Design choice: reuses HuaweiECSDiscovery's already real-PDI-verified
// _sign() method directly (new HuaweiECSDiscovery(config)._sign(req)) rather
// than duplicating the SDK-HMAC-SHA256 crypto block a ninth time. This is
// the same cross-Script-Include delegation HcConnectorEcsSync.js already
// uses for fetch/reconcile - HuaweiECSDiscovery.js is untouched (frozen,
// real-PDI verified), only read from. _sign() honors config.accessKey/
// secretKey via HuaweiECSDiscovery's own _explicitCredential mechanism
// (confirmed in that file's initialize()/_getCredential()), so no gs.
// getProperty() call happens here at all - credentials still flow through
// HC Cloud Account.auth_mode -> createCredentialProvider(), same as every
// sync orchestrator.
//
// Which account/region a given CI belongs to is resolved via
// HC Resource Sync State (account/region/native_key columns, keyed by
// resource_type='ecs' + ci=<this CI's sys_id>) - the same table every sync
// orchestrator already writes, just read here instead.
//
// Huawei's batch action API (POST /v1/{project_id}/cloudservers/action,
// Nova-compatible os-start/os-stop/reboot shape) - request body built by
// lib/ecsLifecycleAction.js, mirrored inline below (ServiceNow scoped
// scripts cannot require() - keep both in sync, covered by
// check-mirror-drift.js's ninth PAIRS entry).
//
// Response shape NOT yet real-PDI confirmed - Huawei's docs describe this
// as an async operation typically returning 200/202 with an empty body;
// this file treats any 2xx as success and logs the raw body, correcting on
// the first real error per this project's standing "let the real error
// decide" discipline.

// __HC_CONNECTOR_INLINED_LIB__

var HcConnectorEcsLifecycleAction = Class.create();
HcConnectorEcsLifecycleAction.prototype = {
    initialize: function() {
        this.SCOPE = 'x_2021019_huawei_0';
        this.ACCOUNT_TABLE = this.SCOPE + '_hc_cloud_account';
        this.REGION_TABLE = this.SCOPE + '_hc_cloud_region';
        this.SYNC_STATE_TABLE = this.SCOPE + '_hc_resource_sync_state';
        this.RESOURCE_TYPE = 'ecs';
    },

    // ------------------------------------------------------------------
    // UI Action condition helper - true only for CIs this connector
    // actually discovered (never show Start/Stop/Reboot on an unrelated
    // cmdb_ci_vm_instance from another Discovery source).
    // ------------------------------------------------------------------
    isManaged: function(ciSysId) {
        return !!this._resolveContext(ciSysId);
    },

    // ------------------------------------------------------------------
    // Entry point
    // ------------------------------------------------------------------
    // @param ciSysId - cmdb_ci_vm_instance sys_id
    // @param action - 'start'|'stop'|'reboot'
    // @param opts - { hard: boolean } - hard=true requests HARD (power-cycle) instead of SOFT (graceful)
    // @returns {{status: number, body: string}}
    performAction: function(ciSysId, action, opts) {
        var ctx = this._resolveContext(ciSysId);
        if (!ctx) {
            throw new Error('CI ' + ciSysId + ' has no active HC Resource Sync State row for resource_type=ecs - not managed by this connector');
        }

        var provider = createCredentialProvider(ctx.account.auth_mode, {
            propertyReader: function(name) { return gs.getProperty(gs.getCurrentScopeName() + '.' + name); },
            accountId: ctx.account.account_id
        });
        var credentials = provider.getCredentials(); // throws NotImplemented for 'agency' - surfaces as a real error to the caller

        var disco = new HuaweiECSDiscovery({
            region: ctx.region.region,
            projectId: ctx.region.project_id,
            accessKey: credentials.accessKey,
            secretKey: credentials.secretKey
        });

        var host = 'ecs.' + ctx.region.region + '.myhuaweicloud.com';
        var pathname = '/v1/' + ctx.region.project_id + '/cloudservers/action';
        var body = JSON.stringify(this._buildActionRequestBody(action, ctx.nativeKey, opts));

        var signed = disco._sign({ method: 'POST', pathname: pathname, host: host, body: body });

        var request = new sn_ws.RESTMessageV2();
        request.setHttpMethod('POST');
        request.setEndpoint('https://' + host + pathname);
        request.setRequestHeader('Content-Type', signed['Content-Type']);
        request.setRequestHeader('X-Sdk-Date', signed['X-Sdk-Date']);
        request.setRequestHeader('Authorization', signed['Authorization']);
        request.setRequestHeader('host', host);
        request.setRequestBody(body);

        var response = request.execute();
        var status = response.getStatusCode();
        var responseBody = response.getBody();

        if (status < 200 || status >= 300) {
            gs.error('[HcConnectorEcsLifecycleAction] ' + action + ' failed for CI ' + ciSysId +
                ' (server ' + ctx.nativeKey + '): ' + status + ' - ' + responseBody);
            throw new Error('ECS ' + action + ' action failed: HTTP ' + status + ' - ' + responseBody);
        }

        gs.info('[HcConnectorEcsLifecycleAction] ' + action + ' issued for CI ' + ciSysId +
            ' (server ' + ctx.nativeKey + '): HTTP ' + status + ' - ' + responseBody);
        return { status: status, body: responseBody };
    },

    // ------------------------------------------------------------------
    // Resolve which HC Cloud Account/HC Cloud Region a CI belongs to via
    // HC Resource Sync State - the same join every sync orchestrator
    // writes, read here instead of written.
    // ------------------------------------------------------------------
    _resolveContext: function(ciSysId) {
        var stateGr = new GlideRecord(this.SYNC_STATE_TABLE);
        stateGr.addQuery('ci', ciSysId);
        stateGr.addQuery('resource_type', this.RESOURCE_TYPE);
        stateGr.addQuery('status', '!=', 'retired');
        stateGr.query();
        if (!stateGr.next()) return null;

        var nativeKey = stateGr.getValue('native_key');

        var accountGr = new GlideRecord(this.ACCOUNT_TABLE);
        if (!accountGr.get(stateGr.getValue('account'))) return null;

        var regionGr = new GlideRecord(this.REGION_TABLE);
        if (!regionGr.get(stateGr.getValue('region'))) return null;

        return {
            nativeKey: nativeKey,
            account: { sys_id: accountGr.getUniqueValue(), account_id: accountGr.getValue('account_id'), auth_mode: accountGr.getValue('auth_mode') },
            region: { sys_id: regionGr.getUniqueValue(), region: regionGr.getValue('region'), project_id: regionGr.getValue('project_id') }
        };
    },

    // ------------------------------------------------------------------
    // Mirrors lib/ecsLifecycleAction.js's buildActionRequestBody() inline.
    // Keep in sync - covered by check-mirror-drift.js's ninth PAIRS entry.
    // ------------------------------------------------------------------
    _buildActionRequestBody: function(action, serverId, opts) {
        var VALID_ACTIONS = ['start', 'stop', 'reboot'];
        if (VALID_ACTIONS.indexOf(action) === -1) {
            throw new Error('Unknown ECS lifecycle action: ' + action + ' (must be one of ' + VALID_ACTIONS.join(', ') + ')');
        }
        if (!serverId) {
            throw new Error('serverId is required');
        }
        opts = opts || {};
        var mode = opts.hard ? 'HARD' : 'SOFT';
        var servers = [{ id: serverId }];

        if (action === 'start') {
            return { 'os-start': { servers: servers } };
        }
        if (action === 'stop') {
            return { 'os-stop': { servers: servers, type: mode } };
        }
        return { reboot: { type: mode, servers: servers } };
    },

    type: 'HcConnectorEcsLifecycleAction'
};
