// Script Include: HcConnectorVpcSync
// HAND-WRITTEN TEMPLATE - do not paste this file directly into ServiceNow.
// The deployable version is generated by
// scripts/build-script-include.js, which inlines lib/credentialProvider.js,
// lib/resourceLifecycle.js, lib/compositeKey.js, lib/discoveryRunTracker.js,
// and lib/syncStatePlanner.js (module.exports stripped) at the marker below,
// producing docs/generated/HcConnectorVpcSync.generated.js - paste THAT.
//
// Multi-account/region VPC + Subnet + Security Group sync orchestrator (HC
// ITOM Connector Phase 2B, Security Group added in Phase 2C). Sibling to
// service-graph/HcConnectorEcsSync.js, not a refactor of it - that file is
// real-PDI verified and intentionally left untouched. No shared base class
// between the two on purpose, to keep the diff against Phase 2A's proven
// code at exactly zero; reuse happens at the pure lib/ layer below, which
// is already resource-type-agnostic.
//
// For every active HC Cloud Region under every active HC Cloud Account:
//   1. resolve credentials (createCredentialProvider, from HC Cloud
//      Account.auth_mode) - same as HcConnectorEcsSync
//   2. construct a HuaweiVpcDiscovery with explicit config (its
//      fetch/sign/reconcile logic - see
//      servicenow/discovery/HuaweiVpcDiscovery.js)
//   3. fetch vpcs, subnets, AND security groups, then reconcile via ONE
//      IRE call (relations[] needs every side's array indices in the same
//      payload - can't be split across separate createOrUpdateCI calls;
//      this is also why Security Group -> ECS instance relations aren't
//      attempted here, since ECS is a wholly separate discovery run - see
//      HuaweiVpcDiscovery.js's header comment)
//   4. upsert HC Resource Sync State for EACH resource type separately -
//      planSyncStateUpdates (lib/syncStatePlanner.js, unchanged) is called
//      THREE times, once per resource type, since it's already scoped by
//      resource_type via its caller
//   5. run the retirement pass for each resource type - but ONLY if the
//      shared fetch/reconcile phase succeeded; a failure skips straight to
//      recording the error (for ALL THREE resource types' run rows
//      together) and moving to the next region. Same structural guarantee
//      as ECS: "an incomplete sync can never retire a resource."
// One account/region's failure is caught and logged without stopping the
// loop for the others.
//
// Three HC Discovery Run rows per account/region iteration (one per
// resource_type='vpc'/'subnet'/'security_group'), sharing one trace_id to
// link them as "the same underlying fetch" - not a combined resource_type
// string, since hc_discovery_run/RESOURCE-MATRIX.md are both designed
// around one row = one resource type. Adding 'security_group' needed no
// schema change - resource_type is a plain string field, not a choice list.

// __HC_CONNECTOR_INLINED_LIB__

var HcConnectorVpcSync = Class.create();
HcConnectorVpcSync.prototype = {
    initialize: function() {
        this.SCOPE = 'x_2021019_huawei_0';
        this.ACCOUNT_TABLE = this.SCOPE + '_hc_cloud_account';
        this.REGION_TABLE = this.SCOPE + '_hc_cloud_region';
        this.RUN_TABLE = this.SCOPE + '_hc_discovery_run';
        this.SYNC_STATE_TABLE = this.SCOPE + '_hc_resource_sync_state';
        this.CONFIG_TABLE = this.SCOPE + '_hc_connector_config';
        this.RESOURCE_TYPE_VPC = 'vpc';
        this.RESOURCE_TYPE_SUBNET = 'subnet';
        // Phase 2C addition - 'security_group' needed no schema change:
        // hc_discovery_run.resource_type is a plain string field (not a
        // choice list), so a new value here just works.
        this.RESOURCE_TYPE_SECURITY_GROUP = 'security_group';
    },

    // ------------------------------------------------------------------
    // Entry point
    // ------------------------------------------------------------------
    runAll: function() {
        var self = this;
        var accounts = this._getActiveAccounts();
        gs.info('[HcConnectorVpcSync] starting run across ' + accounts.length + ' active account(s)');
        accounts.forEach(function(account) {
            var regions = self._getActiveRegions(account.sys_id);
            regions.forEach(function(region) {
                try {
                    self._runForAccountRegion(account, region);
                } catch (ex) {
                    // Last-resort catch: _runForAccountRegion already isolates fetch/reconcile
                    // failures internally, so reaching here means something unexpected (e.g. a
                    // GlideRecord error building the run/region context itself) - still must not
                    // stop the loop for the remaining accounts/regions.
                    gs.error('[HcConnectorVpcSync] unexpected failure for account=' + account.account_id +
                        ' region=' + region.region + ': ' + ex.message);
                    self._recordRegionError(region.sys_id, ex.message);
                }
            });
        });
        gs.info('[HcConnectorVpcSync] run complete');
    },

    _runForAccountRegion: function(account, region) {
        var startedAtMs = new Date().getTime();
        var traceId = gs.generateGUID(); // one trace id links the vpc+subnet+security_group run triple
        var vpcRunFields = startRun({
            accountSysId: account.sys_id,
            regionSysId: region.sys_id,
            resourceType: this.RESOURCE_TYPE_VPC,
            correlationId: account.account_id + ':' + region.region + ':vpc',
            traceId: traceId,
            startedAtMs: startedAtMs
        });
        var subnetRunFields = startRun({
            accountSysId: account.sys_id,
            regionSysId: region.sys_id,
            resourceType: this.RESOURCE_TYPE_SUBNET,
            correlationId: account.account_id + ':' + region.region + ':subnet',
            traceId: traceId,
            startedAtMs: startedAtMs
        });
        var sgRunFields = startRun({
            accountSysId: account.sys_id,
            regionSysId: region.sys_id,
            resourceType: this.RESOURCE_TYPE_SECURITY_GROUP,
            correlationId: account.account_id + ':' + region.region + ':security_group',
            traceId: traceId,
            startedAtMs: startedAtMs
        });
        var vpcRunSysId = this._insertDiscoveryRun(vpcRunFields);
        var subnetRunSysId = this._insertDiscoveryRun(subnetRunFields);
        var sgRunSysId = this._insertDiscoveryRun(sgRunFields);

        var fetchResult;
        try {
            fetchResult = this._fetchVpcsSubnetsAndSecurityGroups(account, region);
        } catch (fetchEx) {
            gs.error('[HcConnectorVpcSync] fetch failed for account=' + account.account_id +
                ' region=' + region.region + ': ' + fetchEx.message);
            this._recordRegionError(region.sys_id, fetchEx.message);
            this._finishRun(vpcRunSysId, vpcRunFields, { successCount: 0, failCount: 0, errorSummary: fetchEx.message, endedAtMs: new Date().getTime() });
            this._finishRun(subnetRunSysId, subnetRunFields, { successCount: 0, failCount: 0, errorSummary: fetchEx.message, endedAtMs: new Date().getTime() });
            this._finishRun(sgRunSysId, sgRunFields, { successCount: 0, failCount: 0, errorSummary: fetchEx.message, endedAtMs: new Date().getTime() });
            return; // structural guarantee: retirement below is unreachable on fetch failure, for ALL THREE resource types
        }

        var reconcileResult;
        try {
            reconcileResult = this._reconcileAndUpsert(account, region, fetchResult.vpcs, fetchResult.subnets, fetchResult.securityGroups);
        } catch (reconcileEx) {
            gs.error('[HcConnectorVpcSync] reconcile failed for account=' + account.account_id +
                ' region=' + region.region + ': ' + reconcileEx.message);
            this._recordRegionError(region.sys_id, reconcileEx.message);
            this._finishRun(vpcRunSysId, vpcRunFields, { successCount: 0, failCount: fetchResult.vpcs.length, errorSummary: reconcileEx.message, endedAtMs: new Date().getTime() });
            this._finishRun(subnetRunSysId, subnetRunFields, { successCount: 0, failCount: fetchResult.subnets.length, errorSummary: reconcileEx.message, endedAtMs: new Date().getTime() });
            this._finishRun(sgRunSysId, sgRunFields, { successCount: 0, failCount: fetchResult.securityGroups.length, errorSummary: reconcileEx.message, endedAtMs: new Date().getTime() });
            return; // also skip retirement for all three - we don't know which CIs actually got created
        }

        this._finishRun(vpcRunSysId, vpcRunFields, {
            successCount: reconcileResult.vpcSummary.insertCount + reconcileResult.vpcSummary.refreshCount,
            failCount: 0,
            endedAtMs: new Date().getTime()
        });
        this._finishRun(subnetRunSysId, subnetRunFields, {
            successCount: reconcileResult.subnetSummary.insertCount + reconcileResult.subnetSummary.refreshCount,
            failCount: 0,
            endedAtMs: new Date().getTime()
        });
        this._finishRun(sgRunSysId, sgRunFields, {
            successCount: reconcileResult.sgSummary.insertCount + reconcileResult.sgSummary.refreshCount,
            failCount: 0,
            endedAtMs: new Date().getTime()
        });
        this._recordRegionSuccess(region.sys_id);
        gs.info('[HcConnectorVpcSync] account=' + account.account_id + ' region=' + region.region +
            ' done: vpc=' + JSON.stringify(reconcileResult.vpcSummary) + ' subnet=' + JSON.stringify(reconcileResult.subnetSummary) +
            ' security_group=' + JSON.stringify(reconcileResult.sgSummary));
    },

    _finishRun: function(runSysId, runFields, outcome) {
        this._updateDiscoveryRun(runSysId, finishRun(runFields, outcome));
    },

    // ------------------------------------------------------------------
    // Fetch (delegates to HuaweiVpcDiscovery)
    // ------------------------------------------------------------------
    _fetchVpcsSubnetsAndSecurityGroups: function(account, region) {
        var provider = createCredentialProvider(account.auth_mode, {
            propertyReader: function(name) { return gs.getProperty(gs.getCurrentScopeName() + '.' + name); },
            accountId: account.account_id
        });
        var credentials = provider.getCredentials(); // throws NotImplemented for 'agency' - correctly surfaces as a fetch failure above

        var disco = new HuaweiVpcDiscovery({
            region: region.region,
            projectId: region.project_id,
            pageLimit: this._getConnectorConfigValue('vpc_page_limit', 100),
            maxRetryAttempts: this._getConnectorConfigValue('vpc_max_retry_attempts', 3),
            accessKey: credentials.accessKey,
            secretKey: credentials.secretKey
        });

        var vpcs = disco.fetchVPCs(); // throws on a page failure - see HuaweiVpcDiscovery.js
        var subnets = disco.fetchSubnets();
        var securityGroups = disco.fetchSecurityGroups();
        return { disco: disco, vpcs: vpcs, subnets: subnets, securityGroups: securityGroups };
    },

    // ------------------------------------------------------------------
    // Reconcile (delegates to HuaweiVpcDiscovery.reconcileCIs)
    // + upsert HC Resource Sync State (per resource type) + retirement
    // ------------------------------------------------------------------
    _reconcileAndUpsert: function(account, region, vpcs, subnets, securityGroups) {
        var self = this;
        securityGroups = securityGroups || [];

        // Same throwaway-instance reasoning as HcConnectorEcsSync: reconcileCIs
        // doesn't need credentials, only region/accountId (used to identify the
        // shared logical-datacenter/cloud-service-account placeholders), so a
        // fresh instance configured the same way is fine here.
        var disco = new HuaweiVpcDiscovery({ region: region.region, accountId: account.account_id });
        var result = disco.reconcileCIs(vpcs, subnets, securityGroups);

        // reconcileCIs catches its own exceptions internally and returns undefined on
        // failure rather than rethrowing (see HuaweiVpcDiscovery.js) - this is where that
        // silent failure gets converted into a real thrown error our caller can act on.
        if (!result) {
            throw new Error('reconcileCIs returned no result - the IRE call likely failed, see the prior gs.error log from HuaweiVpcDiscovery');
        }
        if (result.hasError) {
            // Conservative, same as HcConnectorEcsSync: treat any reported IRE error as a
            // failure for the whole batch rather than guessing which items succeeded.
            // errorCount is per-item/per-relation in the real IRE response shape, not a
            // top-level field (confirmed via real-PDI testing) - sum it up for a useful count.
            var totalErrors = (result.items || []).reduce(function(sum, item) { return sum + (item.errorCount || 0); }, 0) +
                (result.relations || []).reduce(function(sum, rel) { return sum + (rel.errorCount || 0); }, 0);
            throw new Error('IRE reconciliation reported errors (errorCount=' + totalErrors + ') - see the prior gs.info log for the full result');
        }

        var vpcSeen = vpcs.map(function(v) {
            return { native_key: v.id, ci: self._lookupCiByCorrelationId(v.id, disco.CI_CLASS_VPC) };
        });
        var subnetSeen = subnets.map(function(s) {
            return { native_key: s.id, ci: self._lookupCiByCorrelationId(s.id, disco.CI_CLASS_SUBNET) };
        });
        var sgSeen = securityGroups.map(function(sg) {
            return { native_key: sg.id, ci: self._lookupCiByCorrelationId(sg.id, disco.CI_CLASS_SECURITY_GROUP) };
        });

        var vpcExisting = this._getExistingSyncStateRows(account.sys_id, region.sys_id, this.RESOURCE_TYPE_VPC);
        var subnetExisting = this._getExistingSyncStateRows(account.sys_id, region.sys_id, this.RESOURCE_TYPE_SUBNET);
        var sgExisting = this._getExistingSyncStateRows(account.sys_id, region.sys_id, this.RESOURCE_TYPE_SECURITY_GROUP);

        var missThreshold = this._getConsecutiveMissThreshold();
        var vpcPlan = planSyncStateUpdates(vpcSeen, vpcExisting, { computeNextState: computeNextState, consecutiveMissThreshold: missThreshold });
        var subnetPlan = planSyncStateUpdates(subnetSeen, subnetExisting, { computeNextState: computeNextState, consecutiveMissThreshold: missThreshold });
        var sgPlan = planSyncStateUpdates(sgSeen, sgExisting, { computeNextState: computeNextState, consecutiveMissThreshold: missThreshold });

        this._applyInserts(account, region, this.RESOURCE_TYPE_VPC, vpcPlan.toInsert);
        this._applyInserts(account, region, this.RESOURCE_TYPE_SUBNET, subnetPlan.toInsert);
        this._applyInserts(account, region, this.RESOURCE_TYPE_SECURITY_GROUP, sgPlan.toInsert);
        this._applyRefreshes(vpcPlan.toRefresh);
        this._applyRefreshes(subnetPlan.toRefresh);
        this._applyRefreshes(sgPlan.toRefresh);
        this._applyTransitions(vpcPlan.toTransition);
        this._applyTransitions(subnetPlan.toTransition);
        this._applyTransitions(sgPlan.toTransition);

        return {
            vpcPlan: vpcPlan, subnetPlan: subnetPlan, sgPlan: sgPlan,
            vpcSummary: summarizePlan(vpcPlan), subnetSummary: summarizePlan(subnetPlan), sgSummary: summarizePlan(sgPlan)
        };
    },

    _lookupCiByCorrelationId: function(correlationId, table) {
        var gr = new GlideRecord(table);
        gr.addQuery('correlation_id', correlationId);
        gr.query();
        if (gr.next()) return gr.getUniqueValue();
        return null;
    },

    // ------------------------------------------------------------------
    // HC Resource Sync State reads/writes - resourceType is a PARAMETER
    // here (not an instance-level constant like HcConnectorEcsSync's
    // this.RESOURCE_TYPE), since one run covers two resource types.
    // ------------------------------------------------------------------
    _getExistingSyncStateRows: function(accountSysId, regionSysId, resourceType) {
        var results = [];
        var gr = new GlideRecord(this.SYNC_STATE_TABLE);
        gr.addQuery('account', accountSysId);
        gr.addQuery('region', regionSysId);
        gr.addQuery('resource_type', resourceType);
        gr.query();
        while (gr.next()) {
            results.push({
                sys_id: gr.getUniqueValue(),
                native_key: gr.getValue('native_key'),
                status: gr.getValue('status'),
                consecutive_miss_count: parseInt(gr.getValue('consecutive_miss_count'), 10) || 0
            });
        }
        return results;
    },

    _applyInserts: function(account, region, resourceType, toInsert) {
        var self = this;
        toInsert.forEach(function(entry) {
            var gr = new GlideRecord(self.SYNC_STATE_TABLE);
            gr.initialize();
            gr.account = account.sys_id;
            gr.region = region.sys_id;
            gr.resource_type = resourceType;
            gr.native_key = entry.native_key;
            if (entry.ci) gr.ci = entry.ci;
            gr.last_seen = new GlideDateTime();
            gr.consecutive_miss_count = 0;
            gr.status = 'active';
            gr.insert();
        });
    },

    // Resource-type-agnostic (operate on sys_id) - identical to HcConnectorEcsSync's.
    _applyRefreshes: function(toRefresh) {
        var self = this;
        toRefresh.forEach(function(entry) {
            var gr = new GlideRecord(self.SYNC_STATE_TABLE);
            if (!gr.get(entry.sys_id)) return;
            if (entry.ci) gr.ci = entry.ci;
            gr.last_seen = new GlideDateTime();
            gr.consecutive_miss_count = 0;
            gr.status = 'active';
            gr.update();
        });
    },

    _applyTransitions: function(toTransition) {
        var self = this;
        toTransition.forEach(function(entry) {
            var gr = new GlideRecord(self.SYNC_STATE_TABLE);
            if (!gr.get(entry.sys_id)) return;
            var ciSysId = gr.getValue('ci');
            gr.status = entry.status;
            gr.consecutive_miss_count = entry.consecutive_miss_count;
            gr.update();

            if (entry.justRetired && ciSysId) {
                self._retireCi(ciSysId);
            }
        });
    },

    _retireCi: function(ciSysId) {
        var retiredValue = this._getRetiredInstallStatusValue();
        if (retiredValue == null) {
            gs.warn('[HcConnectorVpcSync] could not resolve cmdb_ci.install_status "Retired" choice value - CI ' +
                ciSysId + ' was retired in HC Resource Sync State but NOT in CMDB, fix manually');
            return;
        }
        var gr = new GlideRecord('cmdb_ci');
        if (!gr.get(ciSysId)) return;
        gr.install_status = retiredValue;
        gr.update();
        gs.info('[HcConnectorVpcSync] retired CI ' + ciSysId);
    },

    _getRetiredInstallStatusValue: function() {
        var gr = new GlideRecord('sys_choice');
        gr.addQuery('name', 'cmdb_ci');
        gr.addQuery('element', 'install_status');
        gr.addQuery('label', 'Retired');
        gr.query();
        if (gr.next()) return gr.getValue('value');
        return null;
    },

    // ------------------------------------------------------------------
    // HC Discovery Run reads/writes - identical to HcConnectorEcsSync's
    // ------------------------------------------------------------------
    _insertDiscoveryRun: function(runFields) {
        var snFields = toServiceNowDiscoveryRunFields(runFields);
        var gr = new GlideRecord(this.RUN_TABLE);
        gr.initialize();
        gr.account = snFields.account;
        gr.region = snFields.region;
        gr.resource_type = snFields.resource_type;
        gr.state = snFields.state;
        gr.started = this._msToGlideDateTime(snFields.started);
        gr.success_count = snFields.success_count;
        gr.fail_count = snFields.fail_count;
        gr.correlation_id = snFields.correlation_id;
        gr.trace_id = snFields.trace_id;
        gr.dry_run = snFields.dry_run;
        return gr.insert();
    },

    _updateDiscoveryRun: function(sysId, runFields) {
        var snFields = toServiceNowDiscoveryRunFields(runFields);
        var gr = new GlideRecord(this.RUN_TABLE);
        if (!gr.get(sysId)) return;
        gr.state = snFields.state;
        if (snFields.ended != null) gr.ended = this._msToGlideDateTime(snFields.ended);
        gr.success_count = snFields.success_count;
        gr.fail_count = snFields.fail_count;
        if (snFields.error_summary) gr.error_summary = snFields.error_summary;
        gr.update();
    },

    _msToGlideDateTime: function(ms) {
        var gdt = new GlideDateTime();
        gdt.setNumericValue(ms);
        return gdt;
    },

    // ------------------------------------------------------------------
    // HC Cloud Account / HC Cloud Region reads + status writes - identical
    // to HcConnectorEcsSync's
    // ------------------------------------------------------------------
    _getActiveAccounts: function() {
        var results = [];
        var gr = new GlideRecord(this.ACCOUNT_TABLE);
        gr.addQuery('active', true);
        gr.query();
        while (gr.next()) {
            results.push({
                sys_id: gr.getUniqueValue(),
                account_id: gr.getValue('account_id'),
                auth_mode: gr.getValue('auth_mode')
            });
        }
        return results;
    },

    _getActiveRegions: function(accountSysId) {
        var results = [];
        var gr = new GlideRecord(this.REGION_TABLE);
        gr.addQuery('account', accountSysId);
        gr.addQuery('active', true);
        gr.addQuery('sync_enabled', true);
        gr.query();
        while (gr.next()) {
            results.push({
                sys_id: gr.getUniqueValue(),
                region: gr.getValue('region'),
                project_id: gr.getValue('project_id')
            });
        }
        return results;
    },

    _recordRegionError: function(regionSysId, message) {
        var gr = new GlideRecord(this.REGION_TABLE);
        if (!gr.get(regionSysId)) return;
        gr.last_error = message;
        gr.update();
    },

    _recordRegionSuccess: function(regionSysId) {
        var gr = new GlideRecord(this.REGION_TABLE);
        if (!gr.get(regionSysId)) return;
        gr.last_success = new GlideDateTime();
        gr.last_error = '';
        gr.update();
    },

    // ------------------------------------------------------------------
    // HC Connector Config reads - identical to HcConnectorEcsSync's
    // ------------------------------------------------------------------
    _getConnectorConfigValue: function(key, defaultValue) {
        var gr = new GlideRecord(this.CONFIG_TABLE);
        gr.addQuery('key', key);
        gr.query();
        if (gr.next()) return gr.getValue('value');
        return defaultValue;
    },

    _getConsecutiveMissThreshold: function() {
        var val = this._getConnectorConfigValue('consecutive_miss_threshold', null);
        if (val == null) return undefined; // let resourceLifecycle's own default apply
        var parsed = parseInt(val, 10);
        return isNaN(parsed) ? undefined : parsed;
    },

    type: 'HcConnectorVpcSync'
};
