// Script Include: HcConnectorEvsSync
// HAND-WRITTEN TEMPLATE - do not paste this file directly into ServiceNow.
// The deployable version is generated by
// scripts/build-script-include.js, which inlines lib/credentialProvider.js,
// lib/resourceLifecycle.js, lib/compositeKey.js, lib/discoveryRunTracker.js,
// and lib/syncStatePlanner.js (module.exports stripped) at the marker below,
// producing docs/generated/HcConnectorEvsSync.generated.js - paste THAT.
//
// Multi-account/region EVS (disk) sync orchestrator (HC ITOM Connector
// Phase 2C). Sibling to HcConnectorEcsSync.js/HcConnectorVpcSync.js, not a
// refactor of either - both are real-PDI verified and intentionally left
// untouched.
//
// No relation to ECS is attempted (see
// servicenow/discovery/HuaweiEvsDiscovery.js's header comment for the
// real, confirmed reason: relations[].parent/child are hard-typed as a
// Java Integer server-side, so a real ECS CI sys_id can't be used in
// place of an array index - a genuine platform limitation, tested and
// confirmed, not a guess). Structure is otherwise identical to
// HcConnectorEcsSync.js: for every active
// HC Cloud Region under every active HC Cloud Account, resolve credentials,
// fetch, reconcile via IRE, upsert HC Resource Sync State, retire on
// disappearance - only reaching retirement if fetch+reconcile both
// succeeded. One account/region's failure is caught and logged without
// stopping the loop for the others.

// __HC_CONNECTOR_INLINED_LIB__

var HcConnectorEvsSync = Class.create();
HcConnectorEvsSync.prototype = {
    initialize: function() {
        this.SCOPE = 'x_2021019_huawei_0';
        this.ACCOUNT_TABLE = this.SCOPE + '_hc_cloud_account';
        this.REGION_TABLE = this.SCOPE + '_hc_cloud_region';
        this.RUN_TABLE = this.SCOPE + '_hc_discovery_run';
        this.SYNC_STATE_TABLE = this.SCOPE + '_hc_resource_sync_state';
        this.CONFIG_TABLE = this.SCOPE + '_hc_connector_config';
        this.RESOURCE_TYPE = 'evs';
    },

    // ------------------------------------------------------------------
    // Entry point
    // ------------------------------------------------------------------
    runAll: function() {
        var self = this;
        var accounts = this._getActiveAccounts();
        gs.info('[HcConnectorEvsSync] starting run across ' + accounts.length + ' active account(s)');
        accounts.forEach(function(account) {
            var regions = self._getActiveRegions(account.sys_id);
            regions.forEach(function(region) {
                try {
                    self._runForAccountRegion(account, region);
                } catch (ex) {
                    gs.error('[HcConnectorEvsSync] unexpected failure for account=' + account.account_id +
                        ' region=' + region.region + ': ' + ex.message);
                    self._recordRegionError(region.sys_id, ex.message);
                }
            });
        });
        gs.info('[HcConnectorEvsSync] run complete');
    },

    _runForAccountRegion: function(account, region) {
        var startedAtMs = new Date().getTime();
        var runFields = startRun({
            accountSysId: account.sys_id,
            regionSysId: region.sys_id,
            resourceType: this.RESOURCE_TYPE,
            correlationId: account.account_id + ':' + region.region,
            traceId: gs.generateGUID(),
            startedAtMs: startedAtMs
        });
        var runRecordSysId = this._insertDiscoveryRun(runFields);

        var fetchResult;
        try {
            fetchResult = this._fetchVolumes(account, region);
        } catch (fetchEx) {
            gs.error('[HcConnectorEvsSync] fetch failed for account=' + account.account_id +
                ' region=' + region.region + ': ' + fetchEx.message);
            this._recordRegionError(region.sys_id, fetchEx.message);
            this._updateDiscoveryRun(runRecordSysId, finishRun(runFields,
                { successCount: 0, failCount: 0, errorSummary: fetchEx.message, endedAtMs: new Date().getTime() }));
            return; // structural guarantee: retirement below is unreachable on fetch failure
        }

        var reconcileResult;
        try {
            reconcileResult = this._reconcileAndUpsert(account, region, fetchResult.volumes);
        } catch (reconcileEx) {
            gs.error('[HcConnectorEvsSync] reconcile failed for account=' + account.account_id +
                ' region=' + region.region + ': ' + reconcileEx.message);
            this._recordRegionError(region.sys_id, reconcileEx.message);
            this._updateDiscoveryRun(runRecordSysId, finishRun(runFields,
                { successCount: 0, failCount: fetchResult.volumes.length, errorSummary: reconcileEx.message, endedAtMs: new Date().getTime() }));
            return; // also skip retirement - we don't know which CIs actually got created
        }

        this._updateDiscoveryRun(runRecordSysId, finishRun(runFields, {
            successCount: reconcileResult.summary.insertCount + reconcileResult.summary.refreshCount,
            failCount: 0,
            endedAtMs: new Date().getTime()
        }));
        this._recordRegionSuccess(region.sys_id);
        gs.info('[HcConnectorEvsSync] account=' + account.account_id + ' region=' + region.region +
            ' done: ' + JSON.stringify(reconcileResult.summary));
    },

    // ------------------------------------------------------------------
    // Fetch (delegates to HuaweiEvsDiscovery)
    // ------------------------------------------------------------------
    _fetchVolumes: function(account, region) {
        var provider = createCredentialProvider(account.auth_mode, {
            propertyReader: function(name) { return gs.getProperty(gs.getCurrentScopeName() + '.' + name); },
            accountId: account.account_id
        });
        var credentials = provider.getCredentials(); // throws NotImplemented for 'agency' - correctly surfaces as a fetch failure above

        var disco = new HuaweiEvsDiscovery({
            region: region.region,
            projectId: region.project_id,
            pageLimit: this._getConnectorConfigValue('evs_page_limit', 100),
            maxRetryAttempts: this._getConnectorConfigValue('evs_max_retry_attempts', 3),
            accessKey: credentials.accessKey,
            secretKey: credentials.secretKey
        });

        var volumes = disco.fetchVolumes(); // throws on a page failure - see HuaweiEvsDiscovery.js
        return { disco: disco, volumes: volumes };
    },

    // ------------------------------------------------------------------
    // Reconcile (delegates to HuaweiEvsDiscovery.reconcileCIs)
    // + upsert HC Resource Sync State + retirement
    // ------------------------------------------------------------------
    _reconcileAndUpsert: function(account, region, volumes) {
        var self = this;

        var disco = new HuaweiEvsDiscovery({ region: region.region, accountId: account.account_id });
        var result = disco.reconcileCIs(volumes);

        if (!result) {
            throw new Error('reconcileCIs returned no result - the IRE call likely failed, see the prior gs.error log from HuaweiEvsDiscovery');
        }
        if (result.hasError) {
            var totalErrors = (result.items || []).reduce(function(sum, item) { return sum + (item.errorCount || 0); }, 0) +
                (result.relations || []).reduce(function(sum, rel) { return sum + (rel.errorCount || 0); }, 0);
            throw new Error('IRE reconciliation reported errors (errorCount=' + totalErrors + ') - see the prior gs.info log for the full result');
        }

        var seenRecords = volumes.map(function(v) {
            return { native_key: v.id, ci: self._lookupCiByCorrelationId(v.id) };
        });

        var existingRows = this._getExistingSyncStateRows(account.sys_id, region.sys_id);
        var plan = planSyncStateUpdates(seenRecords, existingRows, {
            computeNextState: computeNextState,
            consecutiveMissThreshold: this._getConsecutiveMissThreshold()
        });

        this._applyInserts(account, region, plan.toInsert);
        this._applyRefreshes(plan.toRefresh);
        this._applyTransitions(plan.toTransition);

        return { plan: plan, summary: summarizePlan(plan) };
    },

    _lookupCiByCorrelationId: function(correlationId) {
        var gr = new GlideRecord('cmdb_ci_storage_volume');
        gr.addQuery('correlation_id', correlationId);
        gr.query();
        if (gr.next()) return gr.getUniqueValue();
        return null;
    },

    // ------------------------------------------------------------------
    // HC Resource Sync State reads/writes - identical to HcConnectorEcsSync's
    // ------------------------------------------------------------------
    _getExistingSyncStateRows: function(accountSysId, regionSysId) {
        var results = [];
        var gr = new GlideRecord(this.SYNC_STATE_TABLE);
        gr.addQuery('account', accountSysId);
        gr.addQuery('region', regionSysId);
        gr.addQuery('resource_type', this.RESOURCE_TYPE);
        gr.query();
        while (gr.next()) {
            results.push({
                sys_id: gr.getUniqueValue(),
                native_key: gr.getValue('native_key'),
                status: gr.getValue('status'),
                consecutive_miss_count: parseInt(gr.getValue('consecutive_miss_count'), 10) || 0
            });
        }
        return results;
    },

    _applyInserts: function(account, region, toInsert) {
        var self = this;
        toInsert.forEach(function(entry) {
            var gr = new GlideRecord(self.SYNC_STATE_TABLE);
            gr.initialize();
            gr.account = account.sys_id;
            gr.region = region.sys_id;
            gr.resource_type = self.RESOURCE_TYPE;
            gr.native_key = entry.native_key;
            if (entry.ci) gr.ci = entry.ci;
            gr.last_seen = new GlideDateTime();
            gr.consecutive_miss_count = 0;
            gr.status = 'active';
            gr.insert();
        });
    },

    _applyRefreshes: function(toRefresh) {
        var self = this;
        toRefresh.forEach(function(entry) {
            var gr = new GlideRecord(self.SYNC_STATE_TABLE);
            if (!gr.get(entry.sys_id)) return;
            if (entry.ci) gr.ci = entry.ci;
            gr.last_seen = new GlideDateTime();
            gr.consecutive_miss_count = 0;
            gr.status = 'active';
            gr.update();
        });
    },

    _applyTransitions: function(toTransition) {
        var self = this;
        toTransition.forEach(function(entry) {
            var gr = new GlideRecord(self.SYNC_STATE_TABLE);
            if (!gr.get(entry.sys_id)) return;
            var ciSysId = gr.getValue('ci');
            gr.status = entry.status;
            gr.consecutive_miss_count = entry.consecutive_miss_count;
            gr.update();

            if (entry.justRetired && ciSysId) {
                self._retireCi(ciSysId);
            }
        });
    },

    _retireCi: function(ciSysId) {
        var retiredValue = this._getRetiredInstallStatusValue();
        if (retiredValue == null) {
            gs.warn('[HcConnectorEvsSync] could not resolve cmdb_ci.install_status "Retired" choice value - CI ' +
                ciSysId + ' was retired in HC Resource Sync State but NOT in CMDB, fix manually');
            return;
        }
        var gr = new GlideRecord('cmdb_ci');
        if (!gr.get(ciSysId)) return;
        gr.install_status = retiredValue;
        gr.update();
        gs.info('[HcConnectorEvsSync] retired CI ' + ciSysId);
    },

    _getRetiredInstallStatusValue: function() {
        var gr = new GlideRecord('sys_choice');
        gr.addQuery('name', 'cmdb_ci');
        gr.addQuery('element', 'install_status');
        gr.addQuery('label', 'Retired');
        gr.query();
        if (gr.next()) return gr.getValue('value');
        return null;
    },

    // ------------------------------------------------------------------
    // HC Discovery Run reads/writes - identical to HcConnectorEcsSync's
    // ------------------------------------------------------------------
    _insertDiscoveryRun: function(runFields) {
        var snFields = toServiceNowDiscoveryRunFields(runFields);
        var gr = new GlideRecord(this.RUN_TABLE);
        gr.initialize();
        gr.account = snFields.account;
        gr.region = snFields.region;
        gr.resource_type = snFields.resource_type;
        gr.state = snFields.state;
        gr.started = this._msToGlideDateTime(snFields.started);
        gr.success_count = snFields.success_count;
        gr.fail_count = snFields.fail_count;
        gr.correlation_id = snFields.correlation_id;
        gr.trace_id = snFields.trace_id;
        gr.dry_run = snFields.dry_run;
        return gr.insert();
    },

    _updateDiscoveryRun: function(sysId, runFields) {
        var snFields = toServiceNowDiscoveryRunFields(runFields);
        var gr = new GlideRecord(this.RUN_TABLE);
        if (!gr.get(sysId)) return;
        gr.state = snFields.state;
        if (snFields.ended != null) gr.ended = this._msToGlideDateTime(snFields.ended);
        gr.success_count = snFields.success_count;
        gr.fail_count = snFields.fail_count;
        if (snFields.error_summary) gr.error_summary = snFields.error_summary;
        gr.update();
    },

    _msToGlideDateTime: function(ms) {
        var gdt = new GlideDateTime();
        gdt.setNumericValue(ms);
        return gdt;
    },

    // ------------------------------------------------------------------
    // HC Cloud Account / HC Cloud Region reads + status writes - identical
    // to HcConnectorEcsSync's
    // ------------------------------------------------------------------
    _getActiveAccounts: function() {
        var results = [];
        var gr = new GlideRecord(this.ACCOUNT_TABLE);
        gr.addQuery('active', true);
        gr.query();
        while (gr.next()) {
            results.push({
                sys_id: gr.getUniqueValue(),
                account_id: gr.getValue('account_id'),
                auth_mode: gr.getValue('auth_mode')
            });
        }
        return results;
    },

    _getActiveRegions: function(accountSysId) {
        var results = [];
        var gr = new GlideRecord(this.REGION_TABLE);
        gr.addQuery('account', accountSysId);
        gr.addQuery('active', true);
        gr.addQuery('sync_enabled', true);
        gr.query();
        while (gr.next()) {
            results.push({
                sys_id: gr.getUniqueValue(),
                region: gr.getValue('region'),
                project_id: gr.getValue('project_id')
            });
        }
        return results;
    },

    _recordRegionError: function(regionSysId, message) {
        var gr = new GlideRecord(this.REGION_TABLE);
        if (!gr.get(regionSysId)) return;
        gr.last_error = message;
        gr.update();
    },

    _recordRegionSuccess: function(regionSysId) {
        var gr = new GlideRecord(this.REGION_TABLE);
        if (!gr.get(regionSysId)) return;
        gr.last_success = new GlideDateTime();
        gr.last_error = '';
        gr.update();
    },

    // ------------------------------------------------------------------
    // HC Connector Config reads - identical to HcConnectorEcsSync's
    // ------------------------------------------------------------------
    _getConnectorConfigValue: function(key, defaultValue) {
        var gr = new GlideRecord(this.CONFIG_TABLE);
        gr.addQuery('key', key);
        gr.query();
        if (gr.next()) return gr.getValue('value');
        return defaultValue;
    },

    _getConsecutiveMissThreshold: function() {
        var val = this._getConnectorConfigValue('consecutive_miss_threshold', null);
        if (val == null) return undefined; // let resourceLifecycle's own default apply
        var parsed = parseInt(val, 10);
        return isNaN(parsed) ? undefined : parsed;
    },

    type: 'HcConnectorEvsSync'
};
